#!/usr/bin/env bash
# display information about subdomains
# Usage: ./1-world_wide_web <domain> <subdomain>

if [ "$#" -eq 2 ]
then
    subdoms=$2
else
    subdoms=("www" "lb-01" "web-01" "web-02")
fi
for subdom in "${subdoms[@]}"
do
    echo -n "The subdomain $subdom"
    dig "$subdom.$1" | grep -A1 "ANSWER SECTION:" | tail -n 1 | awk '{ print " is a "$4 " record and points to " $5}'
done
