#!/usr/bin/env bash
# configures new ubuntu machine with certain nginx requirements
#  Listens on port 80.
#  Returns a page containing "Holberton School" when queried
#  at the root with a curl GET request.

apt-get update
apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.html

service nginx restart
