#!/usr/bin/env bash
# configures new ubuntu machine with certain nginx requirements
#  Listens on port 80.
#  Returns a page containing "Holberton School" when queried
#  at the root with a curl GET request.

sudo apt-get-y update
sudo apt-get -y install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx start
