#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the
# hostname of the server Nginx is running on
# Write 0-custom_http_response-header so that it
# configures a brand new Ubuntu machine to the
# requirements asked in this task

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.html
FILE="/etc/nginx/sites-available/default"
sudo sed -i "22i \\\tadd_header X-Served-By $HOSTNAME;" $FILE
sudo service nginx start
