#!/usr/bin/env bash
# script Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# if no argument passed Ping the IP 5 times
if [ $# -gt 0 ]; then
   ping "$1" -c5
else
   echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
