#!/bin/bash
# Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

i=1;
while ((i <= 20)); do
    if [[ $i == 4 ]]; then
    echo $i
	echo 'bad luck from China'
    elif [[ $i == 8 ]]; then
    echo $i
	echo 'bad luck from Japan'
    elif [[ $i == 17 ]]; then
    echo $i
    echo 'bad luck from Italy'
    else
    echo $i
    fi
    let i++
done
