#!/usr/bin/env bash
# script that changes the users name to nginx
chmod +w /etc/nginx/nginx.conf
var="user nginx;"
sed -i "1s/.*/$var/" /etc/nginx/nginx.conf
sed -i "'s/80 default_server/8080 default_server/' /etc/nginx/sites-available/default"
pkill apahe2
sudo -u nginx service nginx restart
